"""src.storage.storage
========================
Persistence layer for the **AI Research Agent**.

The module offers two public helpers:

* :func:`save_report` – Serialises a research run to a JSON file under
  ``data/reports``.  The filename is derived from the query (slugified) and a
  UTC timestamp, guaranteeing uniqueness and filesystem safety.
* :func:`load_report` – Reads a previously saved JSON file and returns the
  deserialised ``dict``.

Only the Python standard library is used (``pathlib``, ``json``, ``datetime``
and ``logging``) to keep the implementation lightweight and portable.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# Base directory for persisted reports – relative to the project root.
BASE_DIR = Path(__file__).resolve().parents[2] / "data" / "reports"


def _slugify(text: str) -> str:
    """Return a filesystem‑safe slug from *text*.

    The implementation mirrors typical URL slugs: lower‑cased, whitespace and
    punctuation replaced with underscores, and any characters outside the
    alphanumeric‑underscore set stripped.
    """
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", text.strip().lower())
    slug = re.sub(r"_+", "_", slug).strip("_")
    return slug or "report"


def _ensure_directory(path: Path) -> None:
    """Create *path* (and parents) if it does not exist.

    Errors are logged and re‑raised – callers decide how to handle them.
    """
    try:
        path.mkdir(parents=True, exist_ok=True)
        logger.info("Ensured directory exists: %s", path)
    except Exception as exc:  # pragma: no cover – extremely unlikely
        logger.error("Failed to create directory %s: %s", path, exc)
        raise


def save_report(query: str, report: str, sources: List[Dict[str, Any]]) -> str:
    """Persist a research *report* to ``data/reports``.

    Parameters
    ----------
    query:
        The original user query.  Used to generate a readable filename.
    report:
        The markdown (or plain‑text) report generated by the pipeline.
    sources:
        A list of source dictionaries – each should contain ``title``, ``url``
        and ``summary`` keys.  The function does **not** validate the content
        beyond basic type checks.

    Returns
    -------
    str
        The absolute path of the saved JSON file.
    """
    payload: Dict[str, Any] = {
        "query": query,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "report": report,
        "source_count": len(sources),
        "sources": sources,
    }

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-%S")
    slug = _slugify(query)
    filename = f"{timestamp}_{slug}.json"
    file_path = BASE_DIR / filename

    _ensure_directory(BASE_DIR)

    try:
        file_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        logger.info("Report saved to %s", file_path)
    except Exception as exc:
        logger.error("Failed to write report to %s: %s", file_path, exc)
        raise

    return str(file_path)


def load_report(filepath: str) -> Optional[Dict[str, Any]]:
    """Load a previously saved report JSON.

    Returns ``None`` if the file does not exist or cannot be parsed.
    """
    path = Path(filepath)
    if not path.is_file():
        logger.error("Report file does not exist: %s", filepath)
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        logger.info("Report loaded from %s", filepath)
        return data
    except Exception as exc:  # pragma: no cover – defensive
        logger.error("Failed to load report %s: %s", filepath, exc)
        return None

